### PR TITLE
Include full semver version in version.properties

### PR DESCRIPTION
**Pull request by ronaldvaneede**
So it could be interpreted by other (build) scripting for example.

### CODE REVIEW

**Comment by ethauvin** [comment]
@rveede Not a bad idea either. Can you resolve the conflicts with what I just pushed? Thanks.

**Comment by ronaldvaneede** [comment]
Done.

`./gradlew -Dversion.prerelease=betaaa -Dversion.major=22 run` will create this version.properties file:

```#Generated by the Semver Plugin for Gradle
#Thu Apr 11 16:58:14 CEST 2019
version.major=22
version.meta=
version.minor=0
version.patch=0
version.prerelease=betaaa
version.semver=22.0.0-betaaa

**Comment by ethauvin** [comment]
@rveede I've added the ability to set the semver key.

```gradle
semver {
    semverKey = fullversion
}
```
```ini
#version.properties
version.fullversion=1.0.10
```
I haven't incorporated it in the tests yet, so if you have a chance to play with it. I'd appreciate it.

I'm actually thinking of allowing the semver version to be set directly via the command line:

```
./gradlew --Dversion.semver=1.2.1-beta+sha256 ...
```
Thoughts?

Thanks.

**Comment by ronaldvaneede** [comment]
> @rveede I've added the ability to set the semver key.
> 
> ```groovy-gradle
> semver {
>     semverKey = fullversion
> }
> ```
> 
> ```ini
> #version.properties
> version.fullversion=1.0.10
> ```
nice :) 
> 
> I haven't incorporated it in the tests yet, so if you have a chance to play with it. I'd appreciate it.

I will see what I can do.

> I'm actually thinking of allowing the semver version to be set directly via the command line:
> 
> ```
> ./gradlew --Dversion.semver=1.2.1-beta+sha256 ...
> ```
> 
> Thoughts?

I didn't include that because version.semver was calculated from the other variables.
I guess you could do that and then split on the . - and + characters but then you should also taken into account that the prerelease value could also include - characters etc.

**Comment by ethauvin** [comment]
@rveede I did it. Give it a shot. I'm pretty pleased with the parser.

I also converted `major`, `minor` and `patch` to `Int` internally, which has the added benefit of doing a bit of validation on the properties file.

Let me know what you think.

**Comment by ethauvin** [comment]
@rveede Have you been able to break the semver parser?

**Comment by ronaldvaneede** [comment]
haven't been able to test yet but will do asap.

**Pull request merged**
