### PR TITLE
Extended existing tests to include semver property

### PR DESCRIPTION
**Pull request by ronaldvaneede**

### CODE REVIEW

**Review by ethauvin — CHANGES_REQUESTED** [review]
@rveede Thanks. 

I've moved to spek2, can you update the syntax?

**Comment by ronaldvaneede** [comment]
I've merged master and resolved any conflicts

**Comment by ronaldvaneede** [comment]
@ethauvin when did you plan to release a 1.0.0-beta or 1.0.0 version?

**Comment by ethauvin** [comment]
@rveede 1.0.0, as soon as I have the [SemVer Annotation Processor](https://github.com/ethauvin/semver) caught up.

**Comment by ethauvin** [comment]
@rveede I've just released [1.0.0](https://github.com/ethauvin/semver-gradle/releases/tag/1.0.0); I'm not done with the processor, but I figured that might make it easier for you to integrate with your projects.

**Pull request merged**
